const oracledb = require('oracledb');

class OracleModels {

  static async tableExists(connection, tableName) {
    try {
      const query = `SELECT COUNT(*) as count FROM user_tables WHERE table_name = UPPER(:tableName)`;
      const result = await connection.execute(query, { tableName });
      return result.rows[0].COUNT > 0;
    } catch (error) {
      return false;
    }
  }

  static async createEmployeesTable(connection) {
    const exists = await this.tableExists(connection, 'employees');
    if (exists) {
      // Tabla existe
      return;
    }

    const query = `
      CREATE TABLE employees (
        employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name VARCHAR2(50) NOT NULL,
        last_name VARCHAR2(50) NOT NULL,
        email VARCHAR2(100) UNIQUE NOT NULL,
        phone VARCHAR2(20),
        position VARCHAR2(100) NOT NULL,
        department VARCHAR2(50) NOT NULL,
        hire_date DATE DEFAULT SYSDATE,
        salary NUMBER(10,2),
        status VARCHAR2(20) DEFAULT 'ACTIVE',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `;
    await connection.execute(query);
    // Tabla creada
  }

  static async getAllEmployees(connection) {
    const query = 'SELECT * FROM employees WHERE status = \'ACTIVE\' ORDER BY hire_date DESC';
    const result = await connection.execute(query);
    return result.rows;
  }

  static async createFinancialRecordsTable(connection) {
    const exists = await this.tableExists(connection, 'financial_records');
    if (exists) {
      // Tabla existe
      return;
    }

    const query = `
      CREATE TABLE financial_records (
        record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        transaction_type VARCHAR2(20) NOT NULL,
        amount NUMBER(12,2) NOT NULL,
        description VARCHAR2(500),
        category VARCHAR2(100),
        reservation_id NUMBER,
        transaction_date DATE DEFAULT SYSDATE,
        created_by VARCHAR2(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `;
    await connection.execute(query);
    // Tabla creada
  }

  static async getFinancialSummary(connection, startDate, endDate) {
    const query = `
      SELECT 
        transaction_type,
        SUM(amount) as total_amount,
        COUNT(*) as transaction_count
      FROM financial_records 
      WHERE transaction_date BETWEEN :startDate AND :endDate
      GROUP BY transaction_type
    `;
    const result = await connection.execute(query, { startDate, endDate });
    return result.rows;
  }

  static async createInventoryTable(connection) {
    const exists = await this.tableExists(connection, 'inventory');
    if (exists) {
      // Tabla existe
      return;
    }

    const query = `
      CREATE TABLE inventory (
        item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_name VARCHAR2(200) NOT NULL,
        item_type VARCHAR2(50) NOT NULL,
        quantity NUMBER NOT NULL,
        unit_cost NUMBER(10,2),
        supplier VARCHAR2(200),
        purchase_date DATE,
        status VARCHAR2(20) DEFAULT 'AVAILABLE',
        location VARCHAR2(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `;
    await connection.execute(query);
    // Tabla creada
  }

  static async createReportsTable(connection) {
    const exists = await this.tableExists(connection, 'corporate_reports');
    if (exists) {
      // Tabla existe
      return;
    }

    const query = `
      CREATE TABLE corporate_reports (
        report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        report_type VARCHAR2(50) NOT NULL,
        report_name VARCHAR2(200) NOT NULL,
        report_data CLOB,
        generated_by VARCHAR2(100),
        generated_date DATE DEFAULT SYSDATE,
        status VARCHAR2(20) DEFAULT 'GENERATED'
      )
    `;
    await connection.execute(query);
    // Tabla creada
  }

  static async createCorporateClientsTable(connection) {
    const exists = await this.tableExists(connection, 'corporate_clients');
    if (exists) {
      // Tabla existe
      return;
    }

    const query = `
      CREATE TABLE corporate_clients (
        client_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_name VARCHAR2(200) NOT NULL,
        contact_person VARCHAR2(100),
        email VARCHAR2(100),
        phone VARCHAR2(20),
        address VARCHAR2(500),
        tax_id VARCHAR2(50),
        credit_limit NUMBER(12,2),
        payment_terms VARCHAR2(100),
        status VARCHAR2(20) DEFAULT 'ACTIVE',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `;
    await connection.execute(query);
    // Tabla creada
  }

  static async initializeTables(connection) {
    try {
      await this.createEmployeesTable(connection);
      await this.createFinancialRecordsTable(connection);
      await this.createInventoryTable(connection);
      await this.createReportsTable(connection);
      await this.createCorporateClientsTable(connection);
    } catch (error) {
      console.error('Error creando tablas de Oracle:', error.message);
      throw error;
    }
  }

  static async getFinancialDashboard(connection) {
    try {
      const query = `
        SELECT 
          (SELECT SUM(amount) FROM financial_records WHERE transaction_type = 'INCOME' AND transaction_date >= TRUNC(SYSDATE, 'MM')) as monthly_income,
          (SELECT SUM(amount) FROM financial_records WHERE transaction_type = 'EXPENSE' AND transaction_date >= TRUNC(SYSDATE, 'MM')) as monthly_expenses,
          (SELECT COUNT(*) FROM employees WHERE status = 'ACTIVE') as active_employees,
          (SELECT COUNT(*) FROM corporate_clients WHERE status = 'ACTIVE') as active_clients
        FROM dual
      `;
      const result = await connection.execute(query);
      return result.rows[0];
    } catch (error) {
      console.error('Error obteniendo dashboard financiero:', error);
      return null;
    }
  }
}

module.exports = OracleModels;
